# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# Tiny base used by the Docker image asset examples.
FROM public.ecr.aws/nginx/nginx:alpine-slim@sha256:5b52c95c8eeda19dfa9dae708c4e66dce9f0910a6ac5e85dc19779160615b5b2
